export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as OrderSumaries } from './OrderSumaries'
export { default as ProductOverview } from './ProductOverview'
export { default as Checkout } from './Checkout'
export { default as Home } from './Home'
export { default as Payment } from './Payment'
export { default as Product } from './Product'
